// f_underscore.js 0.1.0
// (c) 2012 Kris Jordan
// `f_underscore` is freely distributable under the MIT license.
// Documentation and details at:
// http://krisjordan.com/f_underscore
(function(){var a=function(a){return i(a)};if(typeof exports!=="undefined"){var c=require("underscore");exports.f_=a}else this.f_=a,c=this._;a.VERSION="0.1.0";a.zipObject=function(a,b){var d=c.zip(a,b),f={};c.each(d,function(a){f[a[0]]=a[1]});return f};a.partial=function(a){var b=c.rest(arguments,1);return function(){return a.apply(this,b.concat([].slice.apply(arguments)))}};a.thread=function(){var a=arguments;c.isArray(a[0])&&(a=a[0]);return function(){for(var b=[].slice.apply(arguments),d=0;d<a.length;d++)b=
[a[d].apply(this,b)];return b[0]}};a.callFunction=function(a){return function(b){return b(a)}};a.functionize=function(a){return c.isFunction(a)?a:function(){return a}};a.get=function(a){return function(b){return b[a]}};a.getSet=function(a,b){return function(d){d[a]=b(d[a]);return d}};a.getByProperty=function(a){return function(b){return a[b]}};a.set=function(e,b){var d=a.functionize(b);return function(a){a[e]=d(a);return a}};a.setByProperty=function(e,b){var d=a.functionize(b);return function(a){e[a]=
d(e,a);return e}};a.project=function(e){return function(b){return a.zipObject(e,c.map(e,a.getByProperty(b)))}};a.unaryExpr=function(a,b){if(b===void 0)b=c.identity;return c.isFunction(b)?function(d){return a(b(d))}:function(){return a(b)}};a.binaryExpr=function(a,b,d){if(d===void 0)d=b,b=c.identity;return c.isFunction(b)?c.isFunction(d)?function(c){return a(b(c),d(c))}:function(c){return a(b(c),d)}:c.isFunction(d)?function(c){return a(b,d(c))}:function(){return a(b,d)}};a.methodExpr=function(e){var b=
c.map(c.rest(arguments),a.functionize);return function(a){var f=c.map(b,function(b){return b(a)});a[e]||(a=c.first(f),f=c.rest(f));return a[e].apply(a,f)}};prepend=function(a,b){return(""+b).concat(a)};greaterThan=function(a,b){return a>b};atLeast=function(a,b){return a>=b};lessThan=function(a,b){return a<b};atMost=function(a,b){return a<=b};greaterOf=function(a,b){return a>b?a:b};lesserOf=function(a,b){return a<b?a:b};equality=c.isEqual;inequality=function(){return!equality.apply(this,arguments)};
and=function(a,b){return a&&b};neither=function(a,b){return!a&&!b};or=function(a,b){return a||b};xor=function(a,b){return a&&!b||!a&&b};not=function(a){return!a};a.incr=a.increment=a.partial(a.unaryExpr,function(a){return a+1});a.decr=a.decrement=a.partial(a.unaryExpr,function(a){return a-1});a.sqr=a.square=a.partial(a.unaryExpr,function(a){return a*a});a.not=a.partial(a.unaryExpr,not);a.neg=a.negate=a.partial(a.unaryExpr,function(a){return a*-1});a.add=a.partial(a.binaryExpr,function(a,b){return a+
b});a.sub=a.subtract=a.partial(a.binaryExpr,function(a,b){return a-b});a.mul=a.multiply=a.partial(a.binaryExpr,function(a,b){return a*b});a.div=a.divide=a.partial(a.binaryExpr,function(a,b){return a/b});a.mod=a.modulo=a.partial(a.binaryExpr,function(a,b){return a%b});a.append=a.partial(a.binaryExpr,function(a,b){return(""+a).concat(b)});a.prepend=a.partial(a.binaryExpr,prepend);a.eq=a.isEqual=a.partial(a.binaryExpr,equality);a.neq=a.isNotEqual=a.partial(a.binaryExpr,inequality);a.gt=a.greaterThan=
a.partial(a.binaryExpr,greaterThan);a.gte=a.atLeast=a.partial(a.binaryExpr,atLeast);a.lt=a.lessThan=a.partial(a.binaryExpr,lessThan);a.lte=a.atMost=a.partial(a.binaryExpr,atMost);a.greaterOf=a.partial(a.binaryExpr,greaterOf);a.lesserOf=a.partial(a.binaryExpr,lesserOf);a.and=a.partial(a.binaryExpr,and);a.neither=a.partial(a.binaryExpr,neither);a.or=a.partial(a.binaryExpr,or);a.xor=a.partial(a.binaryExpr,xor);var g="pop,push,reverse,shift,sort,splice,unshift,join,charAt,charCodeAt,fromCharCode,match,replace,search,split,substr,substring,toLowerCase,toUpperCase,concat,indexOf,lastIndexOf,slice".split(",");
c.extend(a,a.zipObject(g,c.map(g,function(c){return a.partial(a.methodExpr,c)})));var h={};c.each(c.functions(a),function(c){h[c]=function(){this._stack.push(a[c].apply(this,arguments));return this}});var i=function(e){var b=[];e!==void 0&&b.push(a.get(e));e=function(){return a.thread(b).apply(this,arguments)};e._stack=b;return c.extend(e,h)}}).call(this);
