// f_underscore.js 0.2.1
// (c) 2012 Kris Jordan
// `f_underscore` is freely distributable under the MIT license.
// Documentation and details at:
// http://krisjordan.com/f_underscore
(function(){var a=function(a){return j(a)};if("undefined"!==typeof exports){var c=require("underscore");exports.f_=a}else this.f_=a,c=this._;a.VERSION="0.2.1";a.zipObject=function(a,b){var d=c.zip(a,b),f={};c.each(d,function(a){f[a[0]]=a[1]});return f};a.partial=function(a){var b=c.rest(arguments,1);return function(){return a.apply(this,b.concat([].slice.apply(arguments)))}};a.thread=function(){var a=arguments;c.isArray(a[0])&&(a=a[0]);return function(){for(var b=[].slice.apply(arguments),d=0;d<a.length;d++)b=
[a[d].apply(this,b)];return b[0]}};a.callFunction=function(a){return function(b){return b(a)}};a.functionize=function(a){return c.isFunction(a)?a:function(){return a}};a.get=function(a){return function(b){return b[a]}};a.getSet=function(a,b){return function(d){d[a]=b(d[a]);return d}};a.getByProperty=function(a){return function(b){return a[b]}};a.set=function(e,b){var d=a.functionize(b);return function(a){a[e]=d(a);return a}};a.setByProperty=function(e,b){var d=a.functionize(b);return function(a){e[a]=
d(e,a);return e}};a.project=function(e){return function(b){return a.zipObject(e,c.map(e,a.getByProperty(b)))}};a.unaryExpr=function(a,b){void 0===b&&(b=c.identity);return c.isFunction(b)?function(d){return a(b(d))}:function(){return a(b)}};a.binaryExpr=function(a,b,d){void 0===d&&(d=b,b=c.identity);return c.isFunction(b)?c.isFunction(d)?function(c){return a(b(c),d(c))}:function(c){return a(b(c),d)}:c.isFunction(d)?function(c){return a(b,d(c))}:function(){return a(b,d)}};a.ternaryExpr=function(e,b,
d,f){void 0===f&&(f=d,d=b,b=c.identity);b=a.functionize(b);d=a.functionize(d);f=a.functionize(f);return function(a){return e(b(a),d(a),f(a))}};a.methodExpr=function(e){var b=c.map(c.rest(arguments),a.functionize);return function(a){var f=c.map(b,function(b){return b(a)});a[e]||(a=c.first(f),f=c.rest(f));return a[e].apply(a,f)}};var g=c.isEqual;a.incr=a.increment=a.partial(a.unaryExpr,function(a){return a+1});a.decr=a.decrement=a.partial(a.unaryExpr,function(a){return a-1});a.sqr=a.square=a.partial(a.unaryExpr,
function(a){return a*a});a.not=a.partial(a.unaryExpr,function(a){return!a});a.neg=a.negate=a.partial(a.unaryExpr,function(a){return-1*a});a.add=a.partial(a.binaryExpr,function(a,b){return a+b});a.sub=a.subtract=a.partial(a.binaryExpr,function(a,b){return a-b});a.mul=a.multiply=a.partial(a.binaryExpr,function(a,b){return a*b});a.div=a.divide=a.partial(a.binaryExpr,function(a,b){return a/b});a.mod=a.modulo=a.partial(a.binaryExpr,function(a,b){return a%b});a.append=a.partial(a.binaryExpr,function(a,
b){return(""+a).concat(b)});a.prepend=a.partial(a.binaryExpr,function(a,b){return(""+b).concat(a)});a.eq=a.isEqual=a.partial(a.binaryExpr,g);a.neq=a.isNotEqual=a.partial(a.binaryExpr,function(){return!g.apply(this,arguments)});a.gt=a.greaterThan=a.partial(a.binaryExpr,function(a,b){return a>b});a.gte=a.atLeast=a.partial(a.binaryExpr,function(a,b){return a>=b});a.lt=a.lessThan=a.partial(a.binaryExpr,function(a,b){return a<b});a.lte=a.atMost=a.partial(a.binaryExpr,function(a,b){return a<=b});a.greaterOf=
a.partial(a.binaryExpr,function(a,b){return a>b?a:b});a.lesserOf=a.partial(a.binaryExpr,function(a,b){return a<b?a:b});a.and=a.partial(a.binaryExpr,function(a,b){return a&&b});a.neither=a.partial(a.binaryExpr,function(a,b){return!a&&!b});a.or=a.partial(a.binaryExpr,function(a,b){return a||b});a.xor=a.partial(a.binaryExpr,function(a,b){return a&&!b||!a&&b});a.ternary=a.partial(a.ternaryExpr,function(a,b,c){return a?b:c});var h="pop,push,reverse,shift,sort,splice,unshift,join,charAt,charCodeAt,fromCharCode,match,replace,search,split,substr,substring,toLowerCase,toUpperCase,concat,indexOf,lastIndexOf,slice".split(",");
c.extend(a,a.zipObject(h,c.map(h,function(c){return a.partial(a.methodExpr,c)})));var i={};c.each(c.functions(a),function(c){i[c]=function(){this._stack.push(a[c].apply(this,arguments));return this}});var j=function(e){var b=[];void 0!==e&&b.push(a.get(e));e=function(){return a.thread(b).apply(this,arguments)};e._stack=b;return c.extend(e,i)}}).call(this);
