// f_underscore.js 0.1.0
// (c) 2012 Kris Jordan
// `f_underscore` is freely distributable under the MIT license.
// For all details and documentation:
// http://krisjordan.com/f_underscore
(function(){var a=function(a){return i(a)};if(typeof exports!=="undefined"){var d=require("underscore");exports.f_=a}else this.f_=a,d=this._;a.VERSION="0.1.0";a.I=a.i=d.identity;a.zipObject=function(a,b){var e=d.zip(a,b),f={};d.each(e,function(a){f[a[0]]=a[1]});return f};a.partial=function(a){var b=d.rest(arguments,1);return function(){return a.apply(this,b.concat([].slice.apply(arguments)))}};a.thread=function(){var a=arguments;d.isArray(a[0])&&(a=a[0]);return function(){for(var b=[].slice.apply(arguments),
e=0;e<a.length;e++)b=[a[e].apply(this,b)];return b[0]}};a.callFunction=function(a){return function(b){return b(a)}};a.functionize=function(a){return d.isFunction(a)?a:function(){return a}};a.get=function(a){return function(b){return b[a]}};a.getSet=function(a,b){return function(e){e[a]=b(e[a]);return e}};a.getByProperty=function(a){return function(b){return a[b]}};a.set=function(c,b){var e=a.functionize(b);return function(a){a[c]=e(a);return a}};a.setByProperty=function(c,b){var e=a.functionize(b);
return function(a){c[a]=e(c,a);return c}};a.project=function(c){return function(b){return a.zipObject(c,d.map(c,a.getByProperty(b)))}};a.unaryExpr=function(c,b){if(b===void 0)b=a.i;return d.isFunction(b)?function(a){return c(b(a))}:function(){return c(b)}};a.binaryExpr=function(c,b,e){if(e===void 0)e=b,b=a.i;return d.isFunction(b)?d.isFunction(e)?function(a){return c(b(a),e(a))}:function(a){return c(b(a),e)}:d.isFunction(e)?function(a){return c(b,e(a))}:function(){return c(b,e)}};prepend=function(a,
b){return(""+b).concat(a)};greaterThan=function(a,b){return a>b};atLeast=function(a,b){return a>=b};lessThan=function(a,b){return a<b};atMost=function(a,b){return a<=b};greaterOf=function(a,b){return a>b?a:b};lesserOf=function(a,b){return a<b?a:b};equality=d.isEqual;inequality=function(){return!equality.apply(this,arguments)};and=function(a,b){return a&&b};neither=function(a,b){return!a&&!b};or=function(a,b){return a||b};xor=function(a,b){return a&&!b||!a&&b};not=function(a){return!a};a.incr=a.increment=
a.partial(a.unaryExpr,function(a){return a+1});a.decr=a.decrement=a.partial(a.unaryExpr,function(a){return a-1});a.sqr=a.square=a.partial(a.unaryExpr,function(a){return a*a});a.not=a.partial(a.unaryExpr,not);a.neg=a.negate=a.partial(a.unaryExpr,function(a){return a*-1});a.add=a.partial(a.binaryExpr,function(a,b){return a+b});a.sub=a.subtract=a.partial(a.binaryExpr,function(a,b){return a-b});a.mul=a.multiply=a.partial(a.binaryExpr,function(a,b){return a*b});a.div=a.divide=a.partial(a.binaryExpr,function(a,
b){return a/b});a.mod=a.modulo=a.partial(a.binaryExpr,function(a,b){return a%b});a.append=a.partial(a.binaryExpr,function(a,b){return(""+a).concat(b)});a.prepend=a.partial(a.binaryExpr,prepend);a.eq=a.isEqual=a.partial(a.binaryExpr,equality);a.neq=a.isNotEqual=a.partial(a.binaryExpr,inequality);a.gt=a.greaterThan=a.partial(a.binaryExpr,greaterThan);a.gte=a.atLeast=a.partial(a.binaryExpr,atLeast);a.lt=a.lessThan=a.partial(a.binaryExpr,lessThan);a.lte=a.atMost=a.partial(a.binaryExpr,atMost);a.greaterOf=
a.partial(a.binaryExpr,greaterOf);a.lesserOf=a.partial(a.binaryExpr,lesserOf);a.and=a.partial(a.binaryExpr,and);a.neither=a.partial(a.binaryExpr,neither);a.or=a.partial(a.binaryExpr,or);a.xor=a.partial(a.binaryExpr,xor);a.methodExpr=function(c){var b=d.map(d.rest(arguments),a.functionize);return function(a){var f=d.map(b,function(b){return b(a)});a[c]||(a=d.first(f),f=d.rest(f));return a[c].apply(a,f)}};var g="pop,push,reverse,shift,sort,splice,unshift,join,charAt,charCodeAt,fromCharCode,match,replace,search,split,substr,substring,toLowerCase,toUpperCase,concat,indexOf,lastIndexOf,slice".split(",");
d.extend(a,a.zipObject(g,d.map(g,function(c){return a.partial(a.methodExpr,c)})));var h={};d.each(d.functions(a),function(c){h[c]=function(){this.stack.push(a[c].apply(this,arguments));return this}});var i=function(c){var b=[];c!==void 0&&b.push(a.get(c));c=function(){return a.thread(b).apply(this,arguments)};c.stack=b;d.extend(c,h);return c}}).call(this);
